### ISSUE TITLE
Autostart don't work

### ISSUE THREAD

**Issue by Auztiin** [webosbrew/custom-screensaver#9]
I have a rooted LG - 65" Class UN8500 Series. Enabling auto start and rebooting does nothing. Just shows the standard fireworks. Although when applying temporarily it seems to show the screensaver as intended. I tried to disable auto start, reboot, enable auto start, and reboot though it always shows the regular fireworks. I turned off the auto start and uninstalled the app then rebooted. After rebooting and reinstalling the app, auto start is automatically enabled. It does not work. Also, the screensaver reverts to the fireworks after being powered off by the remote. I have to keep manually applying temporarily. I am on webOS version 04.50.56

**Comment by Auztiin** [comment]
Also, the screensaver reverts to the fireworks after being powered off by the remote. I have to keep manually applying temporarily.

**Comment by JoelBrenstrum** [comment]
I'm seeing the same behaviour

**Comment by aabytt** [comment]
Install the app, run it, disable autostart and enable again. Check with ssh/telnet if autostart script created in `var/lib/webosbrew/init.d`

**Comment by Auztiin** [comment]
It seems to show the screensaver now but only when I click run screensaver within the app. I have screensaver enabled on the TV but for some reason I don't get any screensavers anymore.

**Comment by Cr0wTom** [comment]
Same here, any solution?

> It seems to show the screensaver now but only when I click run screensaver within the app. I have screensaver enabled on the TV but for some reason I don't get any screensavers anymore.

**Comment by Auztiin** [comment]
Sorry, can't help. Don't know how it got fixed and set itself. Also, have not found a fix for the no screensaver issue. At least the screensaver is set now but only when clicking the button to test though. The TV turns off before a screensaver could pop up. Not sure how the TV now auto shutdowns in like 10-15 minutes of idling. The only auto off feature available says something like 2 or 4 hours lol good enough for me ¯\_(ツ)_/¯

**Comment by throwaway96** [comment]
@Auztiin

> TV now auto shutdowns in like 10-15 minutes of idling

This sounds like `autoOff15Min`, which I believe is enabled by default. I have seen it in the settings menu on at least one webOS version, but I think it's usually not accessible that way. It's always in the instart menu though (System 1, "15Min Force Off"). You can also control it via Luna.

* Get current setting:
  ```
  luna-send -q 'settings.autoOff15Min' -f -n 1 'luna://com.webos.settingsservice/getSystemSettings' '{"keys":["autoOff15Min"],"category":"time"}'
  ```
* Disable:
  ```
  luna-send -n 1 'luna://com.webos.settingsservice/setSystemSettings' '{"settings":{"autoOff15Min":"off"},"category":"time"}'
  ```
* Enable:
  ```
  luna-send -n 1 'luna://com.webos.settingsservice/setSystemSettings' '{"settings":{"autoOff15Min":"on"},"category":"time"}'
  ```

**Comment by Auztiin** [comment]
Is it possible to change that code to 10 or 5 minutes?

**Comment by throwaway96** [comment]
No.
